# DEFAULT PROFILE
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.18"
auto_detect_solc = false
evm_version = "paris"      # default to paris due to lack of PUSH0 support
verbosity = 3
gas_reports = ["*"]
optimize = true
optimizer_runs = 1_000_000
via-ir = false
ffi = false
fs_permissions = []

remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
]

[profile.default.fuzz]
runs = 1000

# CI PROFILE
[profile.ci]
verbosity = 5

[profile.ci.fuzz]
runs = 10_000

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
arbitrum = "${RPC_URL_ARBITRUM}"
avalanche = "${RPC_URL_AVALANCHE}"
fantom = "${RPC_URL_FANTOM}"
goerli = "${RPC_URL_GOERLI}"
optimism = "${RPC_URL_OPTIMISM}"
polygon = "${RPC_URL_POLYGON}"
base = "${RPC_URL_BASE}"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
arbitrum = { key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api" }
avalanche = { key = "${SNOWTRACE_KEY}", url = "https://api.snowtrace.io/api" }
fantom = { key = "${FTMSCAN_KEY}", url = "https://api.ftmscan.com/api" }
goerli = { key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api" }
optimism = { key = "${OPTIMISM_ETHERSCAN_KEY}", url = "https://api-optimistic.etherscan.io/api" }
polygon = { key = "${POLYGONSCAN_KEY}", url = "https://api.polygonscan.com/api" }
base = { key = "${BASESCAN_KEY}", url = "https://basescan.org/api" }
